LANG_TEXTS = {
    "en": {
        "language": "Language",
        "select_folder": "Select Folder",
        "browse": "Browse",
        "sequential": "Sequential",
        "replace": "Replace",
        "prefix": "Prefix",
        "start_number": "Start Number",
        "find": "Find Text",
        "replace_with": "Replace With",
        "prefix_text": "Prefix Text",
        "function": "Function",
        "start": "Start Rename",
        "undo": "Undo Rename",
        "exit": "Exit",
        "original_name": "Original Name",
        "new_name": "New Name",
    },
    "zh_tw": {
        "language": "語言",
        "select_folder": "選擇資料夾",
        "browse": "瀏覽",
        "sequential": "排序",
        "replace": "取代文字",
        "prefix": "前綴",
        "start_number": "起始編號",
        "find": "尋找文字",
        "replace_with": "取代為",
        "prefix_text": "前綴文字",
        "function": "功能",
        "start": "開始重新命名",
        "undo": "還原名稱",
        "exit": "離開",
        "original_name": "原始檔名",
        "new_name": "改名預覽",
    },
    "zh_cn": {
        "language": "语言",
        "select_folder": "选择文件夹",
        "browse": "浏览",
        "sequential": "排序",
        "replace": "替换文字",
        "prefix": "前缀",
        "start_number": "起始编号",
        "find": "查找文字",
        "replace_with": "替换为",
        "prefix_text": "前缀文字",
        "function": "功能",
        "start": "开始重命名",
        "undo": "还原名称",
        "exit": "退出",
        "original_name": "原始文件名",
        "new_name": "新文件名",
    },
    "ja": {
        "language": "言語",
        "select_folder": "フォルダーを選択",
        "browse": "参照",
        "sequential": "連番",
        "replace": "文字を置換",
        "prefix": "接頭辞",
        "start_number": "開始番号",
        "find": "検索文字",
        "replace_with": "置換文字",
        "prefix_text": "接頭文字",
        "function": "機能",
        "start": "名前変更を開始",
        "undo": "元に戻す",
        "exit": "終了",
        "original_name": "元のファイル名",
        "new_name": "新しいファイル名",
    }
}
